### ISSUE TITLE
Make mkdirp an explicit dependency?

### ISSUE THREAD

**Issue by nrempel** [ahmadnassri/mkdirp-promise#66]
Is there a reason that `mkdirp` is a peer dependency? Since this library relies on `mkdirp`, wouldn't it make to list it as a full dependency?

**Comment by ahmadnassri** [comment]
this is fully explained by @domenic on the Node Blog: https://nodejs.org/en/blog/npm/peer-dependencies/

###### tl;dr 

peer dependencies allow `npm` to better select the most compatible version across all dependencies that require `mkdirp`, and since this package is does not rely on any  specific version, its also made to `*`

**Comment by nrempel** [comment]
Cool, thanks for the clarification
